import React from 'react';

export const metadata = {
  title: 'Bella Femme Manager',
  description: 'Generated by App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
